apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nfs-volume
      mountPath: /test
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-client-pvc
