apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-client-pvc-rwx
spec:
  storageClassName: vsphere-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
