apiVersion: v1
kind: Pod
metadata:
  name: nginx-static-pv
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nfs-volume
      mountPath: /test
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: static-file-share-pvc-name
